name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "SwiftOpenAPIGenerator"

  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:
      # Disable strict concurrency checking as it intersects badly with
      # warnings-as-errors on 5.10 and later as SwiftPMs generated test manifest
      # has a non-sendable global property.
      linux_5_10_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
      # TODO: Enable warnings-as-errors on 6.0.
      linux_6_0_arguments_override: "-Xswiftc -strict-concurrency=complete --explicit-target-dependency-import-check error"
      linux_6_1_arguments_override: "-Xswiftc -strict-concurrency=complete --explicit-target-dependency-import-check error"
      linux_nightly_next_arguments_override: "-Xswiftc -strict-concurrency=complete --explicit-target-dependency-import-check error"
      linux_nightly_main_arguments_override: "-Xswiftc -strict-concurrency=complete --explicit-target-dependency-import-check error"
      windows_6_0_enabled: true
      windows_6_1_enabled: true
      windows_nightly_6_1_enabled: true
      windows_nightly_main_enabled: true
      windows_6_0_arguments_override: "--explicit-target-dependency-import-check error"
      windows_6_1_arguments_override: "--explicit-target-dependency-import-check error"
      windows_nightly_6_1_arguments_override: "--explicit-target-dependency-import-check error"
      windows_nightly_main_arguments_override: "--explicit-target-dependency-import-check error"

  cxx-interop:
    name: Cxx interop
    uses: apple/swift-nio/.github/workflows/cxx_interop.yml@main

  macos-tests:
    name: macOS tests
    uses: apple/swift-nio/.github/workflows/macos_tests.yml@main
    with:
      runner_pool: general
      build_scheme: swift-openapi-urlsession
